leftnav:
- identifier: 6312446a-b05d-d258-9114-eea938300fe9
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 968c5798-2a74-f4fd-fa3b-21a3f4951d3a
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: a6d9c602-6672-03c9-0c05-b31e79191c1d
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 75e0602f-6aab-255d-e60b-9e26435ec367
  name: Study Materials
  pageRef: /video_galleries/study-materials/
  weight: 40
- identifier: 49728c74-b451-7429-9506-32549b75e2bb
  name: Related Resources
  pageRef: /pages/related-resources
  weight: 50
